default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(?:vue|[jt]sx?|[cm][jt]s)$
        types: [file]
        additional_dependencies:
          # renovate: datasource=npm
          - eslint@8.56.0
          # renovate: datasource=npm
          - eslint-plugin-vue@9.31.0
          # renovate: datasource=npm
          - "@vue/eslint-config-typescript@12.0.0"
          # renovate: datasource=npm
          - "@vue/eslint-config-prettier@9.0.0"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [html, css, json, yaml, markdown]

  - repo: https://github.com/aentwist/pre-commit-mirrors-commitlint
    rev: v19.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          # renovate: datasource=npm
          - commitlint@19.5.0
          # renovate: datasource=npm
          - "@commitlint/config-conventional@19.5.0"
