default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
      - id: eslint
        files: \.(?:vue|[jt]sx?|[cm][jt]s)$
        types: [file]
        additional_dependencies:
          - eslint@8.53.0
          - eslint-plugin-vue@9.18.0
          - "@vue/eslint-config-typescript@11.0.3"
          - "@vue/eslint-config-prettier@8.0.0"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [html, css, json, yaml, markdown]

  - repo: https://github.com/aentwist/pre-commit-mirrors-commitlint
    rev: v19.0.3
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - commitlint@19.0.3
          - "@commitlint/config-conventional@19.0.3"
